DROP DATABASE IF EXISTS PROYECTO_MODULAR;
CREATE DATABASE IF NOT EXISTS PROYECTO_MODULAR;
USE PROYECTO_MODULAR;

-- ---------------------------------------------------
--				TABLA TEMATICA
-- ---------------------------------------------------
DROP TABLE IF EXISTS TEMATICAS;
CREATE TABLE IF NOT EXISTS TEMATICAS (
	NOMBRE_TEMATICA VARCHAR(150) NOT NULL,
	-- KEYS Y CONSTRAINS 
	PRIMARY KEY (NOMBRE_TEMATICA)
) ENGINE = INNODB;

-- ---------------------------------------------------
--				TABLA GENERO
-- ---------------------------------------------------
DROP TABLE IF EXISTS GENEROS;
CREATE TABLE IF NOT EXISTS GENEROS (
	NOMBRE_GENERO VARCHAR(150) NOT NULL,
	-- KEY Y CONSTRAINS 
	PRIMARY KEY (NOMBRE_GENERO)
) ENGINE = INNODB;

-- ---------------------------------------------------
--				TABLA PRODUCTOS
-- ---------------------------------------------------
DROP TABLE IF EXISTS PRODUCTOS;
CREATE TABLE IF NOT EXISTS PRODUCTOS (
	ID_PRODUCTO INT UNSIGNED AUTO_INCREMENT NOT NULL,
   NOMBRE VARCHAR(125) NOT NULL,
   STOCK INT UNSIGNED NOT NULL,
   PRECIO FLOAT NOT NULL,
   NUM_JUG VARCHAR(4) NOT NULL,
   DESCRIPCION VARCHAR(255) NULL,
   -- RELACIONES 
   TEMATICA VARCHAR(150) NOT NULL,
   -- KEY Y CONSTRAINS 
   PRIMARY KEY (ID_PRODUCTO),
   UNIQUE INDEX AK_NOMBRE (NOMBRE), -- PODRÍAN EXISTIR DOS JUEGOS CON EL MISMO NOMBRE (???) 
   FOREIGN KEY (TEMATICA) REFERENCES TEMATICAS (NOMBRE_TEMATICA)
   	ON DELETE RESTRICT
   	ON UPDATE CASCADE
) ENGINE = INNODB;

-- ---------------------------------------------------
--				TABLA JUEGO
-- ---------------------------------------------------
DROP TABLE IF EXISTS JUEGOS;
CREATE TABLE IF NOT EXISTS JUEGOS (
	JUEGO INT UNSIGNED AUTO_INCREMENT NOT NULL,
	/** KEY Y CONSTRAINS **/
	PRIMARY KEY (JUEGO),
	FOREIGN KEY (JUEGO) REFERENCES PRODUCTOS (ID_PRODUCTO)
		ON DELETE CASCADE
		ON UPDATE CASCADE
) ENGINE = INNODB;

-- ---------------------------------------------------
--				TABLA ACCESORIO
-- ---------------------------------------------------
DROP TABLE IF EXISTS ACCESORIOS;
CREATE TABLE IF NOT EXISTS ACCESORIOS (
	ACCESORIO INT UNSIGNED AUTO_INCREMENT NOT NULL,
	/** KEY Y CONSTRAINS **/
	PRIMARY KEY (ACCESORIO),
	FOREIGN KEY (ACCESORIO) REFERENCES PRODUCTOS (ID_PRODUCTO)
		ON DELETE CASCADE
		ON UPDATE CASCADE
) ENGINE = INNODB;

-- ---------------------------------------------------
--				TABLA PRODUCTO_GENERO
-- ---------------------------------------------------
DROP TABLE IF EXISTS PRODUCTOS_GENEROS;
CREATE TABLE IF NOT EXISTS PRODUCTOS_GENEROS (
	ID_PRODUCTO_GENERO INT UNSIGNED AUTO_INCREMENT NOT NULL,
	PRODUCTO INT UNSIGNED NOT NULL,
	GENERO VARCHAR(150) NOT NULL,
	-- KEYS Y CONSTRAINS 
	PRIMARY KEY (ID_PRODUCTO_GENERO),
	FOREIGN KEY (PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY (GENERO) REFERENCES GENEROS (NOMBRE_GENERO)
		ON DELETE CASCADE
		ON UPDATE CASCADE
) ENGINE = INNODB;

-- ---------------------------------------------------
--				TABLA SUSCRIPCION
-- ---------------------------------------------------
DROP TABLE IF EXISTS SUSCRIPCIONES;
CREATE TABLE IF NOT EXISTS SUSCRIPCIONES (
	DURACION TINYINT NOT NULL,
	-- KEYS Y CONSTRAINS
	PRIMARY KEY (DURACION)
) ENGINE INNODB;

-- ---------------------------------------------------
--				TABLA ROlES
-- ---------------------------------------------------
DROP TABLE IF EXISTS ROLES;
CREATE TABLE IF NOT EXISTS ROLES (
	NOMBRE_ROL VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(150) NULL,
    -- KEYS Y CONSTRAINS 
   PRIMARY KEY (NOMBRE_ROL)
)ENGINE = INNODB;
    

-- ---------------------------------------------------
--				TABLA USUARIO
-- ---------------------------------------------------
DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE IF NOT EXISTS USUARIOS (
	ID_USUARIO INT UNSIGNED AUTO_INCREMENT NOT NULL,
   EMAIL VARCHAR(150) NOT NULL,
   PWD VARCHAR(255) NOT NULL,
   NOMBRE VARCHAR(25) NOT NULL,
   APELLIDOS VARCHAR(100) NOT NULL,
   TELEFONO CHAR(11) NULL,
   FECHA_REGISTRO DATE NOT NULL,
   DIRECCION VARCHAR(150) NULL,
   -- GENERO_FAVORITO  ENUM("Detectives","Estrategia","Guerra","Miedo","Puzzles","Cooperativos", "Individual","Competitivo") NULL,
   -- RELACIONES 
   ROL VARCHAR(50) NOT NULL,
   GENERO_FAVORITO VARCHAR(150) NULL,
   SUSCRIPCION TINYINT NULL,
   RENOVAR BOOLEAN NULL,
   -- KEYS Y CONSTRAINS 
   PRIMARY KEY (ID_USUARIO),
   UNIQUE INDEX AK_EMAIL (EMAIL),
   FOREIGN KEY (ROL) REFERENCES ROLES (NOMBRE_ROL)
   	ON DELETE RESTRICT
   	ON UPDATE CASCADE,
   FOREIGN KEY (GENERO_FAVORITO) REFERENCES GENEROS (NOMBRE_GENERO)
   	ON DELETE SET NULL
   	ON UPDATE CASCADE,
   FOREIGN KEY (SUSCRIPCION) REFERENCES SUSCRIPCIONES (DURACION)
   	ON DELETE SET NULL
   	ON UPDATE CASCADE
) ENGINE = INNODB;

    
-- ---------------------------------------------------
--				TABLA CARRITOS
-- ---------------------------------------------------
DROP TABLE IF EXISTS CARRITOS;
CREATE TABLE IF NOT EXISTS CARRITOS (
	ID_CARRITO INT UNSIGNED AUTO_INCREMENT NOT NULL,
	USUARIO_CARRITO INT UNSIGNED NOT NULL,
	-- KEYS Y CONSTRAINS 
	PRIMARY KEY (ID_CARRITO),
	FOREIGN KEY (USUARIO_CARRITO) REFERENCES USUARIOS (ID_USUARIO)
		ON DELETE CASCADE
		ON UPDATE CASCADE
) ENGINE = INNODB;

-- ---------------------------------------------------
--				TABLA PRODUCTO_CARRITO
-- ---------------------------------------------------
DROP TABLE IF EXISTS PRODUCTO_CARRITO;
CREATE TABLE IF NOT EXISTS PRODUCTO_CARRITO (
	ID_PRODUCTO_CARRITO INT UNSIGNED AUTO_INCREMENT NOT NULL,
	CARRITO INT UNSIGNED NOT NULL,
	PRODUCTO INT UNSIGNED NOT NULL, 
	UNIDADES SMALLINT UNSIGNED NOT NULL,
	-- KEYS Y CONSTRAINS 
	PRIMARY KEY (ID_PRODUCTO_CARRITO),
	FOREIGN KEY (CARRITO) REFERENCES CARRITOS (ID_CARRITO)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY (PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO)
		ON DELETE CASCADE
		ON UPDATE CASCADE
) ENGINE = INNODB;

-- ---------------------------------------------------
--				TABLA CAJAS_SORPRESA
-- ---------------------------------------------------
DROP TABLE IF EXISTS CAJAS_SORPRESA;
CREATE TABLE IF NOT EXISTS CAJAS_SORPRESA (
	ID_CAJA INT UNSIGNED AUTO_INCREMENT NOT NULL,
   NUM_JUG VARCHAR(4) NOT NULL,
   FECHA DATE NOT NULL,
   -- RELACIONES
   TEMATICA VARCHAR(150) NULL,
   GENERO VARCHAR(150) NOT NULL,
   -- KEY Y CONSTRAINS 
   PRIMARY KEY (ID_CAJA),
   UNIQUE INDEX AK_FECHA (FECHA), -- PUEDE SER QUE CONSUMA DEMASIADOS RECURSOS AUNQUE AGILICE LA BÚSQUEDA (??) 
   FOREIGN KEY (TEMATICA) REFERENCES TEMATICAS (NOMBRE_TEMATICA)
   	ON DELETE RESTRICT
   	ON UPDATE CASCADE,
   FOREIGN KEY (GENERO) REFERENCES GENEROS (NOMBRE_GENERO)
   	ON DELETE RESTRICT
   	ON UPDATE CASCADE
) ENGINE = INNODB;

-- ---------------------------------------------------
--				TABLA CAJAS_SORPRESA_PRODUCTO
-- ---------------------------------------------------
DROP TABLE IF EXISTS CAJAS_SORPRESA_PRODUCTO;
CREATE TABLE IF NOT EXISTS CAJAS_SORPRESA_PRODUCTO (
	ID_CAJA_SORPRESA_PRODUCTO INT UNSIGNED AUTO_INCREMENT NOT NULL,
	CAJA_SORPRESA INT UNSIGNED NOT NULL,
   PRODUCTO INT UNSIGNED NOT NULL,
   -- KEY Y CONSTRAINS 
   UNIDADES SMALLINT UNSIGNED NOT NULL,
   PRIMARY KEY (ID_CAJA_SORPRESA_PRODUCTO),
   FOREIGN KEY (CAJA_SORPRESA) REFERENCES CAJAS_SORPRESA (ID_CAJA)
   	ON DELETE CASCADE
   	ON UPDATE CASCADE,
   FOREIGN KEY (PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO)
   	ON DELETE RESTRICT
   	ON UPDATE CASCADE
) ENGINE = INNODB;

-- ---------------------------------------------------
--				TABLA CAJAS_SORPRESA_USUARIO
-- ---------------------------------------------------
DROP TABLE IF EXISTS CAJA_SORPRESA_USUARIO;
CREATE TABLE IF NOT EXISTS CAJA_SORPRESA_USUARIO (
	CAJA_SORPRESA INT UNSIGNED NOT NULL,
	USUARIO INT UNSIGNED NOT NULL,
	-- KEYS Y CONSTRAINS
	PRIMARY KEY (CAJA_SORPRESA, USUARIO),
	FOREIGN KEY (CAJA_SORPRESA) REFERENCES CAJAS_SORPRESA (ID_CAJA)
		ON DELETE RESTRICT
		ON UPDATE CASCADE,
	FOREIGN KEY (USUARIO) REFERENCES USUARIOS (ID_USUARIO)
		ON DELETE CASCADE
		ON UPDATE CASCADE
) ENGINE INNODB;


-- ---------------------------------------------------
--				TABLA PEDIDO
-- ---------------------------------------------------
DROP TABLE IF EXISTS PEDIDOS;
CREATE TABLE IF NOT EXISTS PEDIDOS(
	ID_PEDIDO INT UNSIGNED AUTO_INCREMENT NOT NULL,
   PRECIO FLOAT NOT NULL,
   DIRECCION VARCHAR(150) NOT NULL,
   -- RELACIONES 
   USUARIO_PEDIDO INT UNSIGNED NOT NULL,
   FECHA_PEDIDO DATE NOT NULL,
   FECHA_ENTREGA DATE NOT NULL,
   ENTREGADO BOOLEAN NULL,
   -- KEYS Y CONSTRAINS 
   PRIMARY KEY (ID_PEDIDO),
   FOREIGN KEY (USUARIO_PEDIDO) REFERENCES USUARIOS (ID_USUARIO)
		ON DELETE RESTRICT
      ON UPDATE CASCADE
) ENGINE = INNODB;

-- ---------------------------------------------------
--				TABLA PEDIDO_PRODUCTO
-- ---------------------------------------------------
DROP TABLE IF EXISTS PEDIDO_PRODUCTO;
CREATE TABLE IF NOT EXISTS PEDIDO_PRODUCTO (
	ID_PEDIDO_PRODUCTO INT UNSIGNED AUTO_INCREMENT NOT NULL,
	PEDIDO INT UNSIGNED NOT NULL,
   PRODUCTO INT UNSIGNED NOT NULL,
   UNIDADES TINYINT UNSIGNED NOT NULL,
   -- KEYS Y CONSTRAINS 
   PRIMARY KEY (ID_PEDIDO_PRODUCTO),
   FOREIGN KEY (PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO)
		ON DELETE CASCADE
      ON UPDATE CASCADE,
	FOREIGN KEY (PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO)
		ON DELETE CASCADE
      ON UPDATE CASCADE
) ENGINE = INNODB;

-- ---------------------------------------------------
--				TABLA PARTIDAS
-- ---------------------------------------------------
DROP TABLE IF EXISTS PARTIDAS;
CREATE TABLE IF NOT EXISTS PARTIDAS (
	ID_PARTIDA INT UNSIGNED AUTO_INCREMENT NOT NULL,
   PLAZAS_MIN TINYINT NOT NULL,
   PLAZAS_TOTALES TINYINT NOT NULL,
   FECHA DATE NOT NULL,
   HORA_INICIO TIME(0) NOT NULL,
   DURACION SMALLINT NOT NULL,
   -- RELACIONES 
   DIRECTOR_PARTIDA INT UNSIGNED NOT NULL,
   JUEGO_PARTIDA INT UNSIGNED NOT NULL,
   -- KEYS Y CONSTRAINS 
   PRIMARY KEY (ID_PARTIDA),
   FOREIGN KEY (DIRECTOR_PARTIDA) REFERENCES USUARIOS (ID_USUARIO)
		ON DELETE RESTRICT
      ON UPDATE CASCADE,
	FOREIGN KEY (JUEGO_PARTIDA) REFERENCES JUEGOS (JUEGO)
		ON DELETE RESTRICT
      ON UPDATE CASCADE
) ENGINE = INNODB;

-- ---------------------------------------------------
--				TABLA USUARIO_PARTIDA
-- ---------------------------------------------------
DROP TABLE IF EXISTS USUARIO_REGISTRADO_PARTIDA;
CREATE TABLE IF NOT EXISTS USUARIO_REGISTRADO_PARTIDA (
	ID_PARTIDA_RESERVADA INT UNSIGNED AUTO_INCREMENT NOT NULL,
	USUARIO INT UNSIGNED NOT NULL,
   PARTIDA INT UNSIGNED NOT NULL,
   -- KEYS Y CONSTRAINS 
   PRIMARY KEY (ID_PARTIDA_RESERVADA),
   FOREIGN KEY FK_USUARIO_RESERVO (USUARIO) REFERENCES USUARIOS (ID_USUARIO)
		ON DELETE RESTRICT -- SI UN USUARIO QUIERE BORRAR SU CUENTA CON UNA PARTIDA RESERVADA, NO LE DEJARÁ HASTA QUE CANCELE LA RESERVA 
      ON UPDATE CASCADE,
	FOREIGN KEY FK_PARTIDA_RESERVADA (PARTIDA) REFERENCES PARTIDAS (ID_PARTIDA)
		ON DELETE RESTRICT -- MIENTRAS HAYA PARTIDAS RESERVADAS NO SE PODRÁ BORRAR LA PARTIDA 
      ON UPDATE CASCADE
) ENGINE = INNODB;

-- ---------------------------------------------------
--				TABLA PARTIDA_GENEROS
-- ---------------------------------------------------
DROP TABLE IF EXISTS PARTIDAS_GENEROS;
CREATE TABLE IF NOT EXISTS PARTIDAS_GENEROS(
	ID_GENERO_PARTIDA INT UNSIGNED AUTO_INCREMENT NOT NULL,
	PARTIDA INT UNSIGNED NOT NULL,
	GENERO VARCHAR(150) NOT NULL,
	-- KEYS Y CONSTRAINS
	PRIMARY KEY (ID_GENERO_PARTIDA),
	FOREIGN KEY (PARTIDA) REFERENCES PARTIDAS (ID_PARTIDA)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY (GENERO) REFERENCES GENEROS (NOMBRE_GENERO)
		ON DELETE CASCADE
		ON UPDATE CASCADE
) ENGINE INNODB;